// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 5fgC6e3xtG9mSe5XxMw1h6
// Component: CepGBR_d__4isF
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: EUHAWQvqEbnMq/component

import { useScreenVariants as useScreenVariantspsat7WfJvDgQs } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: Psat7WFJvDGQs/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_dark_saa_s_landing_page.module.css"; // plasmic-import: 5fgC6e3xtG9mSe5XxMw1h6/projectcss
import sty from "./PlasmicPriceCard.module.css"; // plasmic-import: CepGBR_d__4isF/css

export type PlasmicPriceCard__VariantMembers = {
  primary: "primary";
  borders: "flatLeft" | "flatRight" | "flatCenter";
};

export type PlasmicPriceCard__VariantsArgs = {
  primary?: SingleBooleanChoiceArg<"primary">;
  borders?: MultiChoiceArg<"flatLeft" | "flatRight" | "flatCenter">;
};

type VariantPropType = keyof PlasmicPriceCard__VariantsArgs;
export const PlasmicPriceCard__VariantProps = new Array<VariantPropType>(
  "primary",
  "borders"
);

export type PlasmicPriceCard__ArgsType = {};
type ArgPropType = keyof PlasmicPriceCard__ArgsType;
export const PlasmicPriceCard__ArgProps = new Array<ArgPropType>();

export type PlasmicPriceCard__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
  h4?: p.Flex<"h4">;
  button?: p.Flex<typeof Button>;
};

export interface DefaultPriceCardProps {
  primary?: SingleBooleanChoiceArg<"primary">;
  borders?: MultiChoiceArg<"flatLeft" | "flatRight" | "flatCenter">;
  className?: string;
}

function PlasmicPriceCard__RenderFunc(props: {
  variants: PlasmicPriceCard__VariantsArgs;
  args: PlasmicPriceCard__ArgsType;
  overrides: PlasmicPriceCard__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(
    () =>
      Object.assign(
        {},

        props.args
      ),
    [props.args]
  );

  const $props = args;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantspsat7WfJvDgQs()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        {
          [sty.rootborders_flatCenter]: hasVariant(
            variants,
            "borders",
            "flatCenter"
          ),
          [sty.rootborders_flatLeft]: hasVariant(
            variants,
            "borders",
            "flatLeft"
          ),
          [sty.rootborders_flatRight]: hasVariant(
            variants,
            "borders",
            "flatRight"
          ),
          [sty.rootprimary]: hasVariant(variants, "primary", "primary")
        }
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox, {
          [sty.freeBoxborders_flatCenter]: hasVariant(
            variants,
            "borders",
            "flatCenter"
          ),
          [sty.freeBoxborders_flatLeft]: hasVariant(
            variants,
            "borders",
            "flatLeft"
          ),
          [sty.freeBoxborders_flatRight]: hasVariant(
            variants,
            "borders",
            "flatRight"
          ),
          [sty.freeBoxprimary]: hasVariant(variants, "primary", "primary")
        })}
      >
        <h4
          data-plasmic-name={"h4"}
          data-plasmic-override={overrides.h4}
          className={classNames(
            projectcss.all,
            projectcss.h4,
            projectcss.__wab_text,
            sty.h4,
            {
              [sty.h4borders_flatCenter]: hasVariant(
                variants,
                "borders",
                "flatCenter"
              ),
              [sty.h4borders_flatLeft]: hasVariant(
                variants,
                "borders",
                "flatLeft"
              ),
              [sty.h4borders_flatRight]: hasVariant(
                variants,
                "borders",
                "flatRight"
              )
            }
          )}
        >
          {hasVariant(variants, "borders", "flatRight")
            ? "Enterprise"
            : hasVariant(variants, "borders", "flatLeft")
            ? "Free"
            : "Pro"}
        </h4>

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__wWc3U,
            {
              [sty.textborders_flatCenter__wWc3UqNbDl]: hasVariant(
                variants,
                "borders",
                "flatCenter"
              ),
              [sty.textborders_flatLeft__wWc3UAAsel]: hasVariant(
                variants,
                "borders",
                "flatLeft"
              ),
              [sty.textborders_flatRight__wWc3Uuu9Nm]: hasVariant(
                variants,
                "borders",
                "flatRight"
              ),
              [sty.textprimary__wWc3Uv7Bc]: hasVariant(
                variants,
                "primary",
                "primary"
              )
            }
          )}
        >
          {hasVariant(variants, "borders", "flatRight")
            ? "Flexible power and security"
            : hasVariant(variants, "borders", "flatLeft")
            ? "A complete analytics platform."
            : "A complete analytics platform."}
        </div>

        <p.PlasmicImg
          alt={""}
          className={classNames(sty.img__kXfwx)}
          displayHeight={"auto" as const}
          displayMaxHeight={"none" as const}
          displayMaxWidth={"100%" as const}
          displayMinHeight={"0" as const}
          displayMinWidth={"0" as const}
          displayWidth={"auto" as const}
          loading={"lazy" as const}
          src={{
            src: "/plasmic/dark_saa_s_landing_page/images/linePricingpng.png",
            fullWidth: 300,
            fullHeight: 2,
            aspectRatio: undefined
          }}
        />

        {(hasVariant(globalVariants, "screen", "mobileOnly") ? true : true) ? (
          <div
            className={classNames(projectcss.all, sty.columns__irJzp, {
              [sty.columnsprimary__irJzpv7Bc]: hasVariant(
                variants,
                "primary",
                "primary"
              )
            })}
          >
            <div className={classNames(projectcss.all, sty.column__aKm6C)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__i3Mbb, {
                  [sty.imgborders_flatLeft__i3MbbAAsel]: hasVariant(
                    variants,
                    "borders",
                    "flatLeft"
                  )
                })}
                displayHeight={"24px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"24px" as const}
                loading={"lazy" as const}
                src={
                  hasVariant(variants, "borders", "flatLeft")
                    ? {
                        src: "/plasmic/dark_saa_s_landing_page/images/checklistPricingWhitepng.png",
                        fullWidth: 38,
                        fullHeight: 39,
                        aspectRatio: undefined
                      }
                    : {
                        src: "/plasmic/dark_saa_s_landing_page/images/checklistpng.png",
                        fullWidth: 48,
                        fullHeight: 48,
                        aspectRatio: undefined
                      }
                }
              />
            </div>

            <div
              className={classNames(projectcss.all, sty.column__i98YO, {
                [sty.columnborders_flatRight__i98YOuu9Nm]: hasVariant(
                  variants,
                  "borders",
                  "flatRight"
                )
              })}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__dtu0O,
                  {
                    [sty.textborders_flatLeft__dtu0OaAsel]: hasVariant(
                      variants,
                      "borders",
                      "flatLeft"
                    ),
                    [sty.textborders_flatRight__dtu0Ouu9Nm]: hasVariant(
                      variants,
                      "borders",
                      "flatRight"
                    ),
                    [sty.textprimary__dtu0Ov7Bc]: hasVariant(
                      variants,
                      "primary",
                      "primary"
                    )
                  }
                )}
              >
                {hasVariant(variants, "borders", "flatRight")
                  ? "Everything in pro"
                  : hasVariant(variants, "borders", "flatLeft")
                  ? "1 Product"
                  : "Up to 10 projects"}
              </div>
            </div>
          </div>
        ) : null}

        {(
          hasVariant(variants, "borders", "flatCenter")
            ? true
            : hasVariant(variants, "primary", "primary")
            ? true
            : true
        ) ? (
          <div
            className={classNames(projectcss.all, sty.columns__t6JkU, {
              [sty.columnsborders_flatCenter__t6JkUqNbDl]: hasVariant(
                variants,
                "borders",
                "flatCenter"
              ),
              [sty.columnsborders_flatLeft__t6JkUaAsel]: hasVariant(
                variants,
                "borders",
                "flatLeft"
              ),
              [sty.columnsborders_flatRight__t6JkUuu9Nm]: hasVariant(
                variants,
                "borders",
                "flatRight"
              ),
              [sty.columnsprimary__t6JkUv7Bc]: hasVariant(
                variants,
                "primary",
                "primary"
              )
            })}
          >
            <div className={classNames(projectcss.all, sty.column___8TwoN)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__dHSjK, {
                  [sty.imgborders_flatLeft__dHSjKaAsel]: hasVariant(
                    variants,
                    "borders",
                    "flatLeft"
                  )
                })}
                displayHeight={"24px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"24px" as const}
                loading={"lazy" as const}
                src={
                  hasVariant(variants, "borders", "flatLeft")
                    ? {
                        src: "/plasmic/dark_saa_s_landing_page/images/checklistPricingWhitepng.png",
                        fullWidth: 38,
                        fullHeight: 39,
                        aspectRatio: undefined
                      }
                    : {
                        src: "/plasmic/dark_saa_s_landing_page/images/checklistpng.png",
                        fullWidth: 48,
                        fullHeight: 48,
                        aspectRatio: undefined
                      }
                }
              />
            </div>

            <div className={classNames(projectcss.all, sty.column__zJrl4)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__hsOlx,
                  {
                    [sty.textborders_flatCenter__hsOlXqNbDl]: hasVariant(
                      variants,
                      "borders",
                      "flatCenter"
                    ),
                    [sty.textborders_flatLeft__hsOlxaAsel]: hasVariant(
                      variants,
                      "borders",
                      "flatLeft"
                    ),
                    [sty.textborders_flatRight__hsOlXuu9Nm]: hasVariant(
                      variants,
                      "borders",
                      "flatRight"
                    ),
                    [sty.textprimary__hsOlXv7Bc]: hasVariant(
                      variants,
                      "primary",
                      "primary"
                    )
                  }
                )}
              >
                {hasVariant(variants, "borders", "flatRight")
                  ? "Volume discount"
                  : hasVariant(variants, "borders", "flatLeft")
                  ? "Analytics board"
                  : hasVariant(variants, "primary", "primary")
                  ? "Analytics board"
                  : "Up to 10 projects"}
              </div>
            </div>
          </div>
        ) : null}

        {(
          hasVariant(variants, "borders", "flatCenter")
            ? true
            : hasVariant(variants, "borders", "flatLeft")
            ? true
            : hasVariant(variants, "primary", "primary")
            ? true
            : hasVariant(globalVariants, "screen", "mobileOnly")
            ? true
            : true
        ) ? (
          <div
            className={classNames(projectcss.all, sty.columns__gPeq2, {
              [sty.columnsborders_flatCenter__gPeq2QNbDl]: hasVariant(
                variants,
                "borders",
                "flatCenter"
              ),
              [sty.columnsborders_flatLeft__gPeq2AAsel]: hasVariant(
                variants,
                "borders",
                "flatLeft"
              ),
              [sty.columnsprimary__gPeq2V7Bc]: hasVariant(
                variants,
                "primary",
                "primary"
              )
            })}
          >
            <div className={classNames(projectcss.all, sty.column__oyG2H)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__wjUlr, {
                  [sty.imgborders_flatLeft__wjUlrAAsel]: hasVariant(
                    variants,
                    "borders",
                    "flatLeft"
                  )
                })}
                displayHeight={"24px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"24px" as const}
                loading={"lazy" as const}
                src={
                  hasVariant(variants, "borders", "flatLeft")
                    ? {
                        src: "/plasmic/dark_saa_s_landing_page/images/checklistPricingWhitepng.png",
                        fullWidth: 38,
                        fullHeight: 39,
                        aspectRatio: undefined
                      }
                    : {
                        src: "/plasmic/dark_saa_s_landing_page/images/checklistpng.png",
                        fullWidth: 48,
                        fullHeight: 48,
                        aspectRatio: undefined
                      }
                }
              />
            </div>

            <div
              className={classNames(projectcss.all, sty.column__hiirT, {
                [sty.columnborders_flatLeft__hiirTaAsel]: hasVariant(
                  variants,
                  "borders",
                  "flatLeft"
                ),
                [sty.columnborders_flatRight__hiirTuu9Nm]: hasVariant(
                  variants,
                  "borders",
                  "flatRight"
                ),
                [sty.columnprimary__hiirTv7Bc]: hasVariant(
                  variants,
                  "primary",
                  "primary"
                )
              })}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xbaDh,
                  {
                    [sty.textborders_flatLeft__xbaDhAAsel]: hasVariant(
                      variants,
                      "borders",
                      "flatLeft"
                    ),
                    [sty.textprimary__xbaDhv7Bc]: hasVariant(
                      variants,
                      "primary",
                      "primary"
                    )
                  }
                )}
              >
                {hasVariant(variants, "borders", "flatLeft")
                  ? "Insights panel"
                  : hasVariant(variants, "primary", "primary")
                  ? "Analytics board"
                  : "Up to 10 projects"}
              </div>
            </div>

            {(
              hasVariant(variants, "borders", "flatRight")
                ? true
                : hasVariant(variants, "borders", "flatLeft")
                ? true
                : hasVariant(variants, "primary", "primary")
                ? true
                : hasVariant(globalVariants, "screen", "mobileOnly")
                ? true
                : true
            ) ? (
              <div
                className={classNames(projectcss.all, sty.column__pb4Am, {
                  [sty.columnborders_flatLeft__pb4AmAAsel]: hasVariant(
                    variants,
                    "borders",
                    "flatLeft"
                  ),
                  [sty.columnborders_flatRight__pb4Amuu9Nm]: hasVariant(
                    variants,
                    "borders",
                    "flatRight"
                  ),
                  [sty.columnprimary__pb4Amv7Bc]: hasVariant(
                    variants,
                    "primary",
                    "primary"
                  )
                })}
              />
            ) : null}
          </div>
        ) : null}

        {(
          hasVariant(variants, "borders", "flatCenter")
            ? true
            : hasVariant(variants, "borders", "flatLeft")
            ? true
            : hasVariant(variants, "primary", "primary")
            ? true
            : hasVariant(globalVariants, "screen", "mobileOnly")
            ? true
            : false
        ) ? (
          <div
            className={classNames(projectcss.all, sty.columns__mfwt, {
              [sty.columnsborders_flatCenter__mfwtqNbDl]: hasVariant(
                variants,
                "borders",
                "flatCenter"
              ),
              [sty.columnsborders_flatLeft__mfwtAAsel]: hasVariant(
                variants,
                "borders",
                "flatLeft"
              ),
              [sty.columnsprimary__mfwtv7Bc]: hasVariant(
                variants,
                "primary",
                "primary"
              )
            })}
          >
            <div className={classNames(projectcss.all, sty.column__zc4EQ)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__aiXzI, {
                  [sty.imgborders_flatLeft__aiXzIaAsel]: hasVariant(
                    variants,
                    "borders",
                    "flatLeft"
                  )
                })}
                displayHeight={"24px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"24px" as const}
                loading={"lazy" as const}
                src={
                  hasVariant(variants, "borders", "flatLeft")
                    ? {
                        src: "/plasmic/dark_saa_s_landing_page/images/checklistPricingWhitepng.png",
                        fullWidth: 38,
                        fullHeight: 39,
                        aspectRatio: undefined
                      }
                    : {
                        src: "/plasmic/dark_saa_s_landing_page/images/checklistpng.png",
                        fullWidth: 48,
                        fullHeight: 48,
                        aspectRatio: undefined
                      }
                }
              />
            </div>

            <div className={classNames(projectcss.all, sty.column__bHtCv)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ch0SO,
                  {
                    [sty.textborders_flatLeft__ch0SOaAsel]: hasVariant(
                      variants,
                      "borders",
                      "flatLeft"
                    ),
                    [sty.textprimary__ch0SOv7Bc]: hasVariant(
                      variants,
                      "primary",
                      "primary"
                    )
                  }
                )}
              >
                {hasVariant(variants, "borders", "flatLeft")
                  ? "CLI access"
                  : hasVariant(variants, "primary", "primary")
                  ? "Analytics board"
                  : "Up to 10 projects"}
              </div>
            </div>
          </div>
        ) : null}

        {(
          hasVariant(variants, "borders", "flatCenter")
            ? true
            : hasVariant(variants, "primary", "primary")
            ? true
            : false
        ) ? (
          <div
            className={classNames(projectcss.all, sty.columns__mpAwp, {
              [sty.columnsborders_flatCenter__mpAwpqNbDl]: hasVariant(
                variants,
                "borders",
                "flatCenter"
              ),
              [sty.columnsprimary__mpAwpv7Bc]: hasVariant(
                variants,
                "primary",
                "primary"
              )
            })}
          >
            <div className={classNames(projectcss.all, sty.column__reM9U)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__muTha)}
                displayHeight={"24px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"24px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/dark_saa_s_landing_page/images/checklistpng.png",
                  fullWidth: 48,
                  fullHeight: 48,
                  aspectRatio: undefined
                }}
              />
            </div>

            <div className={classNames(projectcss.all, sty.column___3Bg4O)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__ghJk,
                  {
                    [sty.textborders_flatCenter__ghJkqNbDl]: hasVariant(
                      variants,
                      "borders",
                      "flatCenter"
                    ),
                    [sty.textprimary__ghJkv7Bc]: hasVariant(
                      variants,
                      "primary",
                      "primary"
                    )
                  }
                )}
              >
                {"Insights panel"}
              </div>
            </div>
          </div>
        ) : null}

        {(
          hasVariant(variants, "borders", "flatCenter")
            ? true
            : hasVariant(variants, "primary", "primary")
            ? true
            : false
        ) ? (
          <div
            className={classNames(projectcss.all, sty.columns__svmcp, {
              [sty.columnsborders_flatCenter__svmcpqNbDl]: hasVariant(
                variants,
                "borders",
                "flatCenter"
              ),
              [sty.columnsprimary__svmcpv7Bc]: hasVariant(
                variants,
                "primary",
                "primary"
              )
            })}
          >
            <div className={classNames(projectcss.all, sty.column__wWqE)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__lu4Mx)}
                displayHeight={"24px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobileOnly")
                    ? ("16px" as const)
                    : ("24px" as const)
                }
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/dark_saa_s_landing_page/images/checklistpng.png",
                  fullWidth: 48,
                  fullHeight: 48,
                  aspectRatio: undefined
                }}
              />
            </div>

            <div className={classNames(projectcss.all, sty.column___3MOEj)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__spcU,
                  {
                    [sty.textprimary__spcUv7Bc]: hasVariant(
                      variants,
                      "primary",
                      "primary"
                    )
                  }
                )}
              >
                {"CLI access"}
              </div>
            </div>
          </div>
        ) : null}

        {(
          hasVariant(variants, "borders", "flatCenter")
            ? true
            : hasVariant(variants, "primary", "primary")
            ? true
            : false
        ) ? (
          <div
            className={classNames(projectcss.all, sty.columns___9Dw8, {
              [sty.columnsborders_flatCenter___9Dw8QNbDl]: hasVariant(
                variants,
                "borders",
                "flatCenter"
              ),
              [sty.columnsprimary___9Dw8V7Bc]: hasVariant(
                variants,
                "primary",
                "primary"
              )
            })}
          >
            <div className={classNames(projectcss.all, sty.column__pnyGc)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__fXvdC)}
                displayHeight={"24px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"24px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/dark_saa_s_landing_page/images/checklistpng.png",
                  fullWidth: 48,
                  fullHeight: 48,
                  aspectRatio: undefined
                }}
              />
            </div>

            <div className={classNames(projectcss.all, sty.column__mA5Ou)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___6DaNd,
                  {
                    [sty.textprimary___6DaNdv7Bc]: hasVariant(
                      variants,
                      "primary",
                      "primary"
                    )
                  }
                )}
              >
                {"Automation features"}
              </div>
            </div>
          </div>
        ) : null}

        {(
          hasVariant(variants, "borders", "flatCenter")
            ? true
            : hasVariant(variants, "primary", "primary")
            ? true
            : false
        ) ? (
          <div
            className={classNames(projectcss.all, sty.columns__qnXay, {
              [sty.columnsborders_flatCenter__qnXaYqNbDl]: hasVariant(
                variants,
                "borders",
                "flatCenter"
              ),
              [sty.columnsprimary__qnXaYv7Bc]: hasVariant(
                variants,
                "primary",
                "primary"
              )
            })}
          >
            <div className={classNames(projectcss.all, sty.column__brs8H)}>
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__kFrco)}
                displayHeight={"24px" as const}
                displayMaxHeight={"none" as const}
                displayMaxWidth={"100%" as const}
                displayMinHeight={"0" as const}
                displayMinWidth={"0" as const}
                displayWidth={"24px" as const}
                loading={"lazy" as const}
                src={{
                  src: "/plasmic/dark_saa_s_landing_page/images/checklistpng.png",
                  fullWidth: 48,
                  fullHeight: 48,
                  aspectRatio: undefined
                }}
              />
            </div>

            <div className={classNames(projectcss.all, sty.column__h1N6P)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___55Ojn,
                  {
                    [sty.textprimary___55OjNv7Bc]: hasVariant(
                      variants,
                      "primary",
                      "primary"
                    )
                  }
                )}
              >
                {"Team features"}
              </div>
            </div>
          </div>
        ) : null}

        <p.PlasmicImg
          alt={""}
          className={classNames(sty.img___7T42A)}
          displayHeight={"auto" as const}
          displayMaxHeight={"none" as const}
          displayMaxWidth={"100%" as const}
          displayMinHeight={"0" as const}
          displayMinWidth={"0" as const}
          displayWidth={"auto" as const}
          loading={"lazy" as const}
          src={{
            src: "/plasmic/dark_saa_s_landing_page/images/linePricingpng.png",
            fullWidth: 300,
            fullHeight: 2,
            aspectRatio: undefined
          }}
        />

        {(
          hasVariant(variants, "borders", "flatCenter")
            ? true
            : hasVariant(variants, "borders", "flatRight")
            ? true
            : hasVariant(variants, "borders", "flatLeft")
            ? true
            : false
        ) ? (
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__cNqcw,
              {
                [sty.textborders_flatCenter__cNqcWqNbDl]: hasVariant(
                  variants,
                  "borders",
                  "flatCenter"
                ),
                [sty.textborders_flatLeft__cNqcwaAsel]: hasVariant(
                  variants,
                  "borders",
                  "flatLeft"
                ),
                [sty.textborders_flatRight__cNqcWuu9Nm]: hasVariant(
                  variants,
                  "borders",
                  "flatRight"
                )
              }
            )}
          >
            {hasVariant(variants, "borders", "flatCenter")
              ? "$ 50"
              : hasVariant(variants, "borders", "flatRight")
              ? "$ 800"
              : "$ 0"}
          </div>
        ) : null}

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__bgi7H,
            {
              [sty.textborders_flatCenter__bgi7HqNbDl]: hasVariant(
                variants,
                "borders",
                "flatCenter"
              ),
              [sty.textborders_flatLeft__bgi7HAAsel]: hasVariant(
                variants,
                "borders",
                "flatLeft"
              ),
              [sty.textborders_flatRight__bgi7Huu9Nm]: hasVariant(
                variants,
                "borders",
                "flatRight"
              )
            }
          )}
        >
          {hasVariant(variants, "borders", "flatRight")
            ? "Starting price, customizable"
            : hasVariant(variants, "borders", "flatLeft")
            ? "Free Forever"
            : "per project/month"}
        </div>

        {(
          hasVariant(variants, "borders", "flatRight")
            ? true
            : hasVariant(variants, "borders", "flatLeft")
            ? true
            : true
        ) ? (
          <Button
            data-plasmic-name={"button"}
            data-plasmic-override={overrides.button}
            className={classNames("__wab_instance", sty.button, {
              [sty.buttonborders_flatCenter]: hasVariant(
                variants,
                "borders",
                "flatCenter"
              ),
              [sty.buttonborders_flatLeft]: hasVariant(
                variants,
                "borders",
                "flatLeft"
              ),
              [sty.buttonborders_flatRight]: hasVariant(
                variants,
                "borders",
                "flatRight"
              ),
              [sty.buttonprimary]: hasVariant(variants, "primary", "primary")
            })}
            color={
              hasVariant(variants, "borders", "flatLeft")
                ? ("white" as const)
                : ("blue" as const)
            }
            endIcon={
              <svg
                className={classNames(projectcss.all, sty.svg__l7Wp5)}
                role={"img"}
              />
            }
            link={"#" as const}
            startIcon={
              <svg
                className={classNames(projectcss.all, sty.svg__voRiJ)}
                role={"img"}
              />
            }
          >
            <div
              className={classNames(
                projectcss.all,
                projectcss.__wab_text,
                sty.text__lTPjK,
                {
                  [sty.textborders_flatCenter__lTPjKqNbDl]: hasVariant(
                    variants,
                    "borders",
                    "flatCenter"
                  ),
                  [sty.textborders_flatLeft__lTPjKaAsel]: hasVariant(
                    variants,
                    "borders",
                    "flatLeft"
                  ),
                  [sty.textborders_flatRight__lTPjKuu9Nm]: hasVariant(
                    variants,
                    "borders",
                    "flatRight"
                  )
                }
              )}
            >
              {hasVariant(variants, "borders", "flatCenter")
                ? "Go Become pro"
                : hasVariant(variants, "borders", "flatRight")
                ? "Everything is yours"
                : hasVariant(variants, "borders", "flatLeft")
                ? "Claim Free"
                : "Go Become pro"}
            </div>
          </Button>
        ) : null}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "h4", "button"],
  freeBox: ["freeBox", "h4", "button"],
  h4: ["h4"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  h4: "h4";
  button: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicPriceCard__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicPriceCard__VariantsArgs;
    args?: PlasmicPriceCard__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicPriceCard__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicPriceCard__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicPriceCard__ArgProps,
          internalVariantPropNames: PlasmicPriceCard__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicPriceCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPriceCard";
  } else {
    func.displayName = `PlasmicPriceCard.${nodeName}`;
  }
  return func;
}

export const PlasmicPriceCard = Object.assign(
  // Top-level PlasmicPriceCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    h4: makeNodeComponent("h4"),
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicPriceCard
    internalVariantProps: PlasmicPriceCard__VariantProps,
    internalArgProps: PlasmicPriceCard__ArgProps
  }
);

export default PlasmicPriceCard;
/* prettier-ignore-end */
